apiVersion: sources.knative.dev/v1alpha2
kind: SinkBinding
metadata:
  name: bind-drug-file-source
spec:
  subject:
    apiVersion: batch/v1
    kind: Job
    selector:
      matchLabels:
        app: drug-file-source
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: drug-processor
  ceOverrides:
    extensions:
      sink: bound
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: drug-processor
spec:
  template:
    spec:
      containers:
      - env:
        - name: S3_BUCKET
          value: druglist
        envFrom:
        - secretRef:
            name: s3-access
        image: docker.io/murugappans/drug-processor:v1
